### ISSUE TITLE
Where can I found the ACCManager command?

### ISSUE THREAD

**Issue by gamcoh** [cedricrey/ac-connector#1]
Hi, in the README you say that I have to create connections with the command `ACCManager` but I don't know where to found it.

**Comment by gamcoh** [comment]
For those who are searching for the same thing the command is under `node_modules/.bin/ACCManager`

**Comment by cedricrey** [comment]
Hello, sorry for the delay, but you seem have found the command.
I'm sorry because I believed that adding the "bin" section in the package.json : 
`"bin": {
    "ACCManager": "./startUI.js"
  }`
will add the "ACCManager" into the local environnement PATH (I thought it linked every "bin" into the npm executable PATH), and will allow user to launch "ACCManager" from anywhere, but it doesn't.
The command is `node_modules/.bin/ACCManager`, thank you
